# Generated by Django 4.1.5 on 2023-01-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='current_user', max_length=60),
        ),
    ]
