# Generated by Django 4.1.5 on 2023-01-19 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 54, 34, 302389, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
